# Generated by Django 2.1.7 on 2020-04-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
